# Generated by Django 4.0.2 on 2022-02-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='skills',
        ),
        migrations.AlterField(
            model_name='data',
            name='created_at',
            field=models.FloatField(default=1644488665.283648),
        ),
    ]
